{% set version = '1.0.6' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-nhmmfdr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - https://github.com/cran/NHMMfdr/archive/{{ version }}.tar.gz
  md5: 895809224cccfee3d2d6b4292c90baad

build:
  number: 1006
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
    - r-locfdr
  run:
    - r-base
    - r-mass
    - r-locfdr

test:
  commands:
    - $R -e "library('NHMMfdr')"           # [not win]
    - "\"%R%\" -e \"library('NHMMfdr')\""  # [win]

about:
  home: http://www.ams.sunysb.edu/~pfkuan/NHMMfdr/
  license: GPL-2.0-or-later
  summary: The NHMMfdr package implements the non-homogeneous Hidden Markov Model based FDR control
    as described in Kuan et al., 2011 for multiple comparison adjustment under dependence.
    It allows for prior information to be incorporated in the model to improve detection
    of significant tests.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: NHMMfdr
# Type: Package
# Title: Compute FDR under dependence using NHMM
# Version: 1.0.6
# Date: 2013-03-04
# Author: Pei Fen Kuan <peifen.kuan@stonybrook.edu>
# Maintainer: Pei Fen Kuan <peifen.kuan@stonybrook.edu>
# Depends: R (>= 2.10.0), MASS, locfdr
# Description: The NHMMfdr package implements the non-homogeneous Hidden Markov Model based FDR control as described in Kuan et al., 2011 for multiple comparison adjustment under dependence. It allows for prior information to be incorporated in the model to improve detection of significant tests.
# License: GPL (>= 2)
# LazyLoad: yes
# Packaged: 2014-03-28 01:56:25 UTC; peifenkuan
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2014-03-28 07:18:34
