travis:
  secure:
    BINSTAR_TOKEN: DsszqtsZ2pBbRxj33HT5vFp9VGrevC/jaxQNIw8JSfrk7xjr6gLrxO+FxcHgKMRcWg4ScomOeT1Y9UOXDy4dnZFm7OlSOyxp0lChqjA5OVHWfyzQzE8SIjJkFnzdpgIMCnyhEGm+eh/e0GBHjoP1Hg5fsc/iuNr2VzLCzPktNr4aBbb+spspf7Asbi50KXDzIUfer5l+BlPdWxE7QtXU42/r+50lPEOHkxMfq26b8MjEeTUv+h5mLzCo+MKshW2gI+dFBj29GHeSwCxIRbc5MudflsAKL8BacgB60PaesRs9gEhP0bFynbejCrtGtOs+eBBIdBRNe6nCbIlL2QhmxsNU7YYn0Og8EZ08H++eSX+2c0VimM8+i80E7/H0YXhP1r2jjI2DyxMNPbwKaNzzSzFGgiHwJI6aFV6Gyd6IgdT2x6bye0X3J2RL4Hz/5f5X8mJ3zJtmOx7E6zXpBDn7Qga4nqqHW8OnB4Yq1O4NzCWGYbLzZ5UDSzknJHyH7jZx1pxSMTllMvSiREQXGKYifxMUYXw9Q9mWLsI8qu4dIEeeo8zfeYVjucmoOk2OJDI5wZiGYP3EIFOzwMUOZrXnG0+DJfz3hGyr/ai7uJgA9Xkdzl5FLFF/zWNJkBt/9QHU4IAa8CJdolgcC8RkJJv5anLRlEklNODKPNCYaKFrrVs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
