travis:
  secure:
    BINSTAR_TOKEN: eyf9HwIosIVJWqCBiB7iaPyJIx6148zu1f5bV4vh0qGLQieYaTF7A4hoIlmISaMUhU9nuj14XifJwg3WCxclmIi6dp0NBcOcONYVF562odS213QVc9FVGM5OF5Wj7AEqD6lVAE0RUp0KS2DB0mRVF7WApQUZWPyMg+CYO24c0f29VCE2GujYZL5WsL58ukt+512t27uI67EzJ/qlLJpeMkuRAnVjyMGInYq+FoqzWzhFmYu4/JZcrs2zxj/4jpUD/rHVF5zz0fJB3zu9mLbQqj9IMQNw71hD4/QaJny3EShruQFkuAMh8TzI4jf0YXIzMqDZOH1VX5iumvk5w/toNtmrJs3qyPKYmm/p1S5sO8bFdigXoMbFMP1j6A3VQI3upO5JJx089Gi7ri6jIxm6bby+9DdAUiykFwkqwOJlsG77ZAygvru0y1uiAsKQRThQNFmYsRL82cVnpC7AEFgUuoodqp+oH+YChyhIDth+AlhnO78mG8WBH7Sm8hRf2GFYJnko07Igy6ciox0NHC9J+4NAbTmJ+Rj0ZvQGu2dgYHL2vdTj6+oLEANkYux7Ac7y7nsXcJtDdXnfPG+oD+vdQYqOmEW19p8JukWXDPcDsZ3OXkV1/bUqcYwMAmSBQQY1lWNiPcIl4/WF4so8C1fPLfeqUtBsu1awk8ZdGmIlUjg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
